### PR TITLE
Cm 25  partial classes in c#

### PR DESCRIPTION
**Pull request by sternet**
Adding the new project

### CODE REVIEW

**Comment by CodeMazeBlog** [comment]
retest this please

**Comment by sternet** [comment]
what do you mean? rerun the dotnet tests? all is good:

[image: image.png]

also PR seemed to be in good shape:

[image: image.png]

what didn't work?

**Comment by CodeMazeBlog** [comment]
Hi @sternet Don't worry about that. This is our command to Jenkins to run the tests again, not to you :)

**Comment by sternet** [comment]
Ok, thanks :) NP

**Pull request merged**
