### PR TITLE
CM-655: Difference Between Returning and Awaiting a Task in an Async Method in C#

### PR DESCRIPTION
**Pull request by ullahahsan1983**

### CODE REVIEW

**Comment by ullahahsan1983** [comment]
@markacker , great thanks for taking care of the naming standards. But the build is broken for a .DS_Store file. Please let me know if I need to look into this?

**Comment by markacker** [comment]
I’m not sure why this occurred. Perhaps because I am running Visual Studio on a Mac? If you have any ideas on how to fix it would be appreciated – I was trying to avoid having you fix the naming convention.

From: Ahsan Ullah ***@***.***>
Date: Friday, February 24, 2023 at 7:54 PM
To: CodeMazeBlog/CodeMazeGuides ***@***.***>
Cc: markacker ***@***.***>, Mention ***@***.***>
Subject: Re: [CodeMazeBlog/CodeMazeGuides] CM-655: Difference Between Returning and Awaiting a Task in an Async Method in C# (PR #898)

@markacker<https://github.com/markacker> , great thanks for taking care of the naming standards. But the build is broken for a .DS_Store file. Please let me know if I need to look into this?

**Comment by ullahahsan1983** [comment]
@markacker , yes, exactly this is because of Mac. No worries, I'm fixing this now.

**Comment by ullahahsan1983** [comment]
@markacker , it's fixed now but I need to force push. So if it needs further changes from your side, you will need to reset your local branch. Again, thanks for doing this for me.

**Comment by markacker** [comment]
Thank you! It’s probably best if I avoid using Visual Studio on my Mac if I need to make any changes, I’m going to setup a Windows PC for that.

From: Ahsan Ullah ***@***.***>
Date: Friday, February 24, 2023 at 8:21 PM
To: CodeMazeBlog/CodeMazeGuides ***@***.***>
Cc: markacker ***@***.***>, Mention ***@***.***>
Subject: Re: [CodeMazeBlog/CodeMazeGuides] CM-655: Difference Between Returning and Awaiting a Task in an Async Method in C# (PR #898)

@markacker<https://github.com/markacker> , it's fixed now but I need to force push. So if it needs further changes from your side, you will need to reset your local branch. Again, thanks for doing this for me.

**Pull request merged**
