### PR TITLE
CM-93: ConcurrentDictionary in C#

### PR DESCRIPTION
**Pull request by redeyens**
Hi @vladimir-pecanac-main,
Please review this request together with the article. Link to the article on CM-93.

### CODE REVIEW

**Comment by redeyens** [comment]
retest this please

**Comment by redeyens** [comment]
Hi @vladimir-pecanac-main. I had some unexpected variations in test execution due to concurrency. I expect it will be better after these fixes, but I don't think we can make a completely deterministic test in such conditions. I'm open to any advice you have. 
Also, feel free to squash the changes on PR merge. Thanks.

**Comment by CodeMazeBlog** [comment]
retest this please

**Comment by CodeMazeBlog** [comment]
Hey @redeyens, your last build seems to have broken the Jenkins instance. As far as I can tell, it came to tests, and then no logs have been shown afterward.

I've restored Jenkins, and now the tests pass, but I'll have to check it in detail tomorrow.

**Comment by CodeMazeBlog** [comment]
Great stuff Dusko, we always squash the changes by default. The code looks alright as is, thanks!

**Pull request merged**
