### PR TITLE
CM-391: Implementation of the Compare Arrays in C#

### PR DESCRIPTION
**Pull request by FilipiBraga**
Implementation of the compare arrays in c#.

### CODE REVIEW

**Comment by MarinkoSpasojevic** [comment]
Retest this please

**Comment by CodeMazeBlog** [comment]
please retest

**Comment by CodeMazeBlog** [comment]
retest please

**Comment by CodeMazeBlog** [comment]
retest this please

**Comment by CodeMazeBlog** [comment]
retest this please

**Comment by CodeMazeBlog** [comment]
No, sorry @FilipiBraga this is a phrase to tell Jenkins to retest the build. Seems it got stuck even though the build passed. Let us check with the DevOps guy, okay?

**Pull request merged**
