### PR TITLE
Write to CSV

### PR DESCRIPTION
**Pull request by HasanKurt**

### CODE REVIEW

**Comment by MarinkoSpasojevic** [comment]
retest this please

**Comment by CodeMazeBlog** [comment]
retest this please

**Comment by CodeMazeBlog** [comment]
retest this please

**Comment by CodeMazeBlog** [comment]
retest this please

**Comment by HasanKurt** [comment]
@MarinkoSpasojevic 
Unittest is failing now, have changed that as well but still failing. I will need to take a look at this later.

**Comment by CodeMazeBlog** [comment]
retest this please

**Comment by CodeMazeBlog** [comment]
retest this please

**Comment by CodeMazeBlog** [comment]
retest this please

**Comment by CodeMazeBlog** [comment]
retest this please

**Comment by CodeMazeBlog** [comment]
retest this please

**Pull request merged**
