### PR TITLE
CM-464: Quicksort Algorithm in C# - Fixes

### PR DESCRIPTION
**Pull request by martinchege324**

### CODE REVIEW

**Comment by CodeMazeBlog** [comment]
Build is getting stuck both on Jenkins and for me locally. I've canceled the build so please check out what's happening.

**Comment by martinchege324** [comment]
Let me check

**Comment by CodeMazeBlog** [comment]
retest this please

**Comment by CodeMazeBlog** [comment]
Hey @martinchege324 any updates on this?

**Comment by martinchege324** [comment]
Hey @CodeMazeBlog, testing out a few fixes then I will push another version in the course of the day

**Comment by CodeMazeBlog** [comment]
Sounds good.

**Comment by martinchege324** [comment]
Hey @CodeMazeBlog, I have pushed an update that passes all those tests

**Pull request merged**
